# Built with Jekyll 3.2.0

# Setup
title:               Julian's Notes.
tagline:             'I am a production engineer. These are my notes'
description:         'I am a production engineer at Shopify. I work on Developer Infrastructure. These are my notes'
url:                 'http://notes.jnadeau.ca'
baseurl:             ''

gems:
  - jekyll-git_metadata

# About/contact
author:
  name:              Julian Nadeau
  url:               https://twitter.com/jules2689
  email:             julian+notes@jnadeau.ca

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: true

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


